apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: srw
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: srw
    spec:
      containers:
      - name: tolga
        image: srw:2
        # for local development against minikube registry
        imagePullPolicy: Never        
        ports:
        - containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: srw-service
  labels:
    app: srw
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 7007
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: srw